spring:
  cloud:
    bus:
      refresh:
        enabled: true
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 7002
eureka:
  client:
     serviceUrl:
        defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'